// <auto-generated />
using System;
using DotNetAPI.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetAPI.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DotNetAPIContext))]
    [Migration("20250218162449_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetAPI.Domain.OrderDomain.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("OrderBondIsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderBondPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderCustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDifferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OrderDifferenceIsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("OrderIsDelivered")
                        .HasColumnType("bit");

                    b.Property<bool>("OrderIsDispatched")
                        .HasColumnType("bit");

                    b.Property<int>("OrderPriority")
                        .HasColumnType("int");

                    b.Property<int>("OrderProgress")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayPalOrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayUOrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ServiceDate2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ServiceDate3")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
